"""create keyword table

Revision ID: 005d8a6f2064
Revises: b7c96f298cab
Create Date: 2024-09-27 16:34:04.527545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '005d8a6f2064'
down_revision: Union[str, None] = 'b7c96f298cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'keywords',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('chunk_id', sa.Text(), nullable=True),
        sa.Column('created_ts', sa.DateTime(), default=sa.func.now(), nullable=True),
        sa.Column('updated_ts', sa.DateTime(), default=sa.func.now(), onupdate=sa.func.now(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keywords')
    # ### end Alembic commands ###
