"""create chunk table

Revision ID: 344d5e7254bd
Revises: c0ccb4f0b979
Create Date: 2024-09-24 23:14:39.902280

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '344d5e7254bd'
down_revision: Union[str, None] = 'c0ccb4f0b979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'chunks',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('keywords', sa.Text, nullable=False),
        sa.Column('chunk', sa.Text, nullable=False),
        sa.Column('training_document_id', sa.Integer, sa.ForeignKey('trained_documents.id')),
        sa.Column('created_ts', sa.DateTime, default=datetime.now),
        sa.Column('updated_ts', sa.DateTime, default=datetime.now, onupdate=datetime.now)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunks')
    # ### end Alembic commands ###
