"""create my_table

Revision ID: c0ccb4f0b979
Revises: 
Create Date: 2024-09-24 23:08:18.907029

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0ccb4f0b979'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'trained_documents',
        sa.Column('id', sa.Integer, primary_key=True, index=True),
        sa.Column('name', sa.String, nullable=True),
        sa.Column('url', sa.String, nullable=True),
        sa.Column('status', sa.String, nullable=True),
        sa.Column('created_ts', sa.DateTime, default=datetime.now),
        sa.Column('updated_ts', sa.DateTime, default=datetime.now, onupdate=datetime.now)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
