"""Initial migration

Revision ID: 1799c2164da0
Revises: 
Create Date: 2025-02-15 20:21:40.771019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1799c2164da0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trained_documents',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('url', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('created_ts', sa.DateTime(), nullable=True),
        sa.Column('updated_ts', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('keywords', sa.Text(), nullable=False),
        sa.Column('chunk', sa.Text(), nullable=False),
        sa.Column('training_document_id', sa.Integer(), nullable=True),
        sa.Column('created_ts', sa.DateTime(), nullable=True),
        sa.Column('updated_ts', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['training_document_id'], ['trained_documents.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('chunk_id', sa.Text(), nullable=True),
        sa.Column('created_ts', sa.DateTime(), nullable=True),
        sa.Column('updated_ts', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trained_documents')
    op.drop_table('keywords')
    op.drop_table('chunks')
    # ### end Alembic commands ###
